

import { 
    DataAnalysisIcon, 
    InfographicIcon, 
    FlowChartIcon,
    ResearchCopilotIcon,
    ResearchWriterIcon,
    PromptGeneratorIcon,
    ParaphraserIcon,
    AIHumanizerIcon,
    ContentCreatorIcon,
    InteriorDesignerIcon,
    TranslatorIcon,
    ChatIcon,
    PresentationIcon,
    InfographicVideoIcon
} from './components/Shared.js';

export const AppView = Object.freeze({
  Home: 'home',
  Research: 'research',
  ResearchWriter: 'researchWriter',
  Prompt: 'prompt',
  Design: 'design',
  Translator: 'translator',
  Paraphraser: 'paraphraser',
  ContentCreator: 'contentCreator',
  AIHumanizer: 'aiHumanizer',
  DataAnalysis: 'dataAnalysis',
  PresentationGenerator: 'presentationGenerator',
  InfographicVideo: 'infographicVideo',
  About: 'about',
  Contact: 'contact',
  Pricing: 'pricing',
  SciGeniusChat: 'sciGeniusChat',
  Terms: 'terms',
  Privacy: 'privacy',
  Admin: 'admin',
});

export const Language = Object.freeze({
  EN: 'en',
  AR: 'ar',
});

export const SERVICES = [
    {
        id: AppView.SciGeniusChat,
        titleKey: 'homeCardSciGeniusChatTitle',
        icon: ChatIcon,
        isPremium: false,
    },
    {
        id: AppView.Research,
        titleKey: 'homeCardResearchTitle',
        icon: ResearchCopilotIcon,
        isPremium: false,
    },
    {
        id: AppView.DataAnalysis,
        titleKey: 'homeCardDataAnalysisTitle',
        icon: DataAnalysisIcon,
        isPremium: true,
    },
    {
        id: AppView.ResearchWriter,
        titleKey: 'homeCardResearchWriterTitle',
        icon: ResearchWriterIcon,
        isPremium: false,
    },
    {
        id: AppView.PresentationGenerator,
        titleKey: 'homeCardPresentationGeneratorTitle',
        icon: PresentationIcon,
        isPremium: true,
    },
    {
        id: AppView.InfographicVideo,
        titleKey: 'homeCardInfographicVideoTitle',
        icon: InfographicVideoIcon,
        isPremium: true,
        isAvailable: false,
    },
    {
        id: AppView.Prompt,
        titleKey: 'homeCardPromptTitle',
        icon: PromptGeneratorIcon,
        isPremium: false,
    },
    {
        id: AppView.Paraphraser,
        titleKey: 'homeCardParaphraserTitle',
        icon: ParaphraserIcon,
        isPremium: false,
    },
    {
        id: AppView.AIHumanizer,
        titleKey: 'homeCardAIHumanizerTitle',
        icon: AIHumanizerIcon,
        isPremium: true,
    },
    {
        id: AppView.ContentCreator,
        titleKey: 'homeCardContentCreatorTitle',
        icon: ContentCreatorIcon,
        isPremium: false,
    },
    {
        id: AppView.Design,
        titleKey: 'homeCardDesignTitle',
        icon: InteriorDesignerIcon,
        isPremium: true,
        isAvailable: false,
    },
    {
        id: AppView.Translator,
        titleKey: 'homeCardTranslatorTitle',
        icon: TranslatorIcon,
        isPremium: false,
    },
];

export const SERVICE_VIEW_IDS = SERVICES.map(s => s.id);

export const i18n = {
  [Language.EN]: {
    title: "SciGenius",
    navHome: "Home",
    navServices: "Services",
    navAbout: "About Us",
    navContact: "Contact Us",
    navPricing: "Pricing & Plans",
    navSupport: "Support",
    navTerms: "Terms & Conditions",
    navPrivacy: "Data Security & Privacy",
    navAdmin: "Admin Panel",
    navResearch: "Research Copilot",
    navResearchWriter: "Research Writer",
    navPrompt: "Prompt Generator",
    navDesign: "Interior Designer",
    navTranslator: "AI Translator",
    navParaphraser: "AI Paraphraser",
    navContentCreator: "Content Creator",
    navAIHumanizer: "AI Humanizer",
    navDataAnalysis: "Data Analyzer",
    navPresentationGenerator: "Presentation Generator",
    navInfographicVideo: "Infographic Video Generator",
    navSciGeniusChat: "Speak with SciGenius",
    // Home
    homeWelcome: "Hello, I'm SciGenius",
    homeDescription: "Your multi-faceted AI assistant. How can I help you today?",
    homeCardResearchTitle: "Academic Research Copilot",
    homeCardResearchDesc: "Upload research papers and chat with AI to get summaries, insights, and find related studies",
    homeCardPromptTitle: "Prompt Generator",
    homeCardPromptDesc: "Transform simple ideas into detailed, evocative prompts for AI image and text generation",
    homeCardDesignTitle: "AI Interior Designer",
    homeCardDesignDesc: "Upload a room photo and let AI redesign it in your chosen style",
    homeCardTranslatorTitle: "AI Translator",
    homeCardTranslatorDesc: "Translate text with context-aware AI for nuanced results.",
    homeCardParaphraserTitle: "AI Paraphraser",
    homeCardParaphraserDesc: "Rewrite your text in different tones and styles to improve clarity and impact",
    homeCardContentCreatorTitle: "Content Creator",
    homeCardContentCreatorDesc: "Create blogs, articles, emails, and more with ease by specifying the topic, type, and tone.",
    homeCardResearchWriterTitle: "AI Research Writer",
    homeCardResearchWriterDesc: "Craft academic papers, proposals, and literature reviews with AI assistance.",
    homeCardAIHumanizerTitle: "AI Humanizer",
    homeCardAIHumanizerDesc: "Rewrite AI-generated text to sound more natural and less robotic.",
    homeCardDataAnalysisTitle: "Data Analyzer",
    homeCardDataAnalysisDesc: "Analyze data from documents to generate charts, infographics, and flow charts.",
    homeCardPresentationGeneratorTitle: "AI Presentation Assistant",
    homeCardPresentationGeneratorDesc: "Generate comprehensive presentation outlines based on your topic and goals.",
    homeCardInfographicVideoTitle: "Infographic Video Generator",
    homeCardInfographicVideoDesc: "Transform static text from documents into dynamic, engaging infographic-style videos.",
    homeCardSciGeniusChatTitle: "Speak with SciGenius",
    homeCardSciGeniusChatDesc: "Have a conversation, ask questions, attach files, and search the web.",
    showMore: "Show More",
    showLess: "Show Less",
    // Welcome Modal
    welcomeTitle: "Welcome to SciGenius",
    welcomeDescription: "Your all-in-one AI platform for research, creativity, and design. Let's get started!",
    welcomeStart: "Start Now",
    welcomeAuth: "Login / Register",
    // About Us
    aboutTitle: "About SciGenius",
    aboutVisionTitle: "Our Vision",
    aboutVisionText: "To democratize the power of artificial intelligence, transforming complex technology into a simple, intuitive tool that amplifies human creativity and ingenuity.",
    aboutMissionTitle: "Our Mission",
    aboutMissionText: "We strive to empower users to transform their ideas and regular text into professional, refined commands that fully leverage AI capabilities.",
    aboutValuesTitle: "Our Values",
    aboutValuePrivacy: "Privacy",
    aboutValuePrivacyDesc: "Commitment to protecting user data and ensuring confidentiality.",
    aboutValueTransparency: "Transparency",
    aboutValueTransparencyDesc: "Clarity in how our AI works and the data it uses.",
    aboutValueImprovement: "Improvement",
    aboutValueImprovementDesc: "Continuously enhancing our tools for a better AI interaction.",
    aboutStoryTitle: "Our Story",
    aboutStoryText: "Our story began with a vision to make AI accessible to everyone. We created an advanced tool that transforms regular text into professional commands, simplifying tasks and achieving outstanding results.",
    // Contact Us
    contactTitle: "Get in touch",
    contactDescription: "Have a question or want to chat? We're here to help. Reach out to us through one of the channels below.",
    contactEmailTitle: "Email Us",
    contactEmailDescription: "For support, partnerships, or other inquiries.",
    contactEmailAddress: "roadmap.casa@gmail.com",
    contactTelegramTitle: "Join our Telegram",
    contactTelegramDescription: "Ask questions and engage with the community.",
    contactTelegramHandle: "Join Channel",
    // Pricing
    pricingTitle: "Choose Your Plan",
    pricingDescription: "Unlock the full power of SciGenius and boost your productivity. Choose the plan that's right for you.",
    monthly: "Monthly",
    yearly: "Yearly",
    save20: "Save 20%",
    mostPopular: "Most Popular",
    choosePlan: "Choose Plan",
    getStarted: "Get Started",
    limitedTimeOffer: "Limited Time Offer - 50% OFF",
    originally: "Originally",
    // Payment Modal
    paymentTitle: "Complete Your Purchase",
    paymentFor: "You are subscribing to the",
    cardNumber: "Card Number",
    expiryDate: "Expiry Date (MM/YY)",
    cvc: "CVC",
    payNow: "Pay Now",
    processingPayment: "Processing Payment...",
    paymentSuccess: "Payment Successful!",
    welcomeAboard: "Welcome aboard! You now have full access to SciGenius.",
    // Research
    researchTitle: "Academic Research Copilot",
    researchDescription: "Upload a document to start a conversation, or ask me to find relevant papers.",
    uploadArea: "Drag & drop a file here, or click to select",
    uploading: "Uploading...",
    fileReady: "is ready. Ask me anything about it.",
    askPlaceholder: "Ask a follow-up question...",
    suggestion1: "Summarize the abstract",
    suggestion2: "What are the key findings?",
    suggestion3: "Find related papers",
    thinking: "SciGenius is thinking...",
    sources: "Sources",
    relatedPapers: "Related Papers",
    // SciGenius Chat
    chatTitle: "Speak with SciGenius",
    chatDescription: "Your personal AI assistant. Ask me anything, attach files, or search the web for the latest information.",
    searchWeb: "Search on the web",
    attachFile: "Attach File",
    // Research Writer
    researchWriterTitle: "AI Research Writer",
    researchWriterDescription: "Select a template to get started with your academic writing. Our AI will help you craft well-structured and compelling content.",
    researchProposalTitle: "Research Proposal",
    researchProposalDesc: "Craft a compelling research proposal with a clear structure, from introduction to methodology.",
    literatureReviewTitle: "Literature Review",
    literatureReviewDesc: "Generate a critical and comprehensive literature review for your research paper, thesis, or dissertation.",
    abstractWritingTitle: "Abstract Writing",
    abstractWritingDesc: "Write a powerful and concise abstract for your academic research project, tailored to your needs.",
    thesisStatementTitle: "Thesis Statement",
    thesisStatementDesc: "Develop a strong and clear thesis statement that will make your essay or paper stand out.",
    essayWritingTitle: "Essay Writing",
    essayWritingDesc: "Streamline your essay writing process with step-by-step AI assistance, from outline to conclusion.",
    backToTemplates: "Back to Templates",
    enterTopicFor: "Enter your topic, main points, or draft for the",
    generate: "Generate",
    generating: "Generating...",
    // Prompt
    promptTitle: "Prompt Generator",
    promptDescription: "Provide a simple topic, and I'll expand it into a detailed, evocative prompt for generative AI.",
    promptPlaceholder: "e.g., a futuristic cityscape at sunset",
    generateSimplePrompt: "Simple Prompt",
    generateAdvancedPrompt: "Advanced Prompt",
    generateImagePrompt: "Image Prompt",
    generateVideoPrompt: "Video Prompt",
    copy: "Copy",
    copied: "Copied!",
    tabGenerate: "Generate Prompt",
    tabCheck: "Check Prompt",
    promptCheckerTitle: "AI Prompt Checker",
    promptCheckerDescription: "Analyze, assess, and enhance your existing prompts for better AI results.",
    enterPromptToCheck: "Enter or paste your prompt here for analysis...",
    checkPromptButton: "Analyze Prompt",
    checkingPrompt: "Analyzing...",
    analysisTitle: "Prompt Analysis",
    errorsTitle: "Identified Issues",
    qualityLevelTitle: "Quality Level",
    enhancedPromptTitle: "Enhanced Prompt",
    // Design
    designTitle: "AI Interior Designer",
    designDescription: "Reimagine your space. Upload a photo, choose a room type and style, and let AI do the rest.",
    step1: "1. Upload a Photo",
    step2: "2. Choose Room Type",
    step3: "3. Pick a Style",
    selectRoomType: "Select Room Type",
    roomTypes: { living: "Living Room", bedroom: "Bedroom", kitchen: "Kitchen", office: "Office", dining: "Dining Room", bathroom: "Bathroom" },
    redesign: "Redesign Room",
    redesigning: "Redesigning your room... this may take a moment.",
    before: "Before",
    after: "After",
    aiDescription: "AI Description",
    download: "Download Design",
    // Translator
    translatorTitle: "AI-Powered Translator",
    translatorDescription: "Translate text with context-aware AI for nuanced results.",
    sourceLanguage: "Source Language",
    targetLanguage: "Target Language",
    enterText: "Enter text to translate...",
    translate: "Translate",
    translating: "Translating...",
    confidenceScore: "Confidence Score",
    listen: "Listen",
    documentTranslation: "Document Translation",
    uploadTxt: "Upload a .txt, .md, .pdf or image file",
    simulatedModel: "Simulated AI Model",
    quickPhrases: "Quick Phrases",
    // Paraphraser
    paraphraserTitle: "AI Paraphraser",
    paraphraserDescription: "Rewrite your text. Choose a mode to adjust the tone and style for any occasion.",
    enterTextToParaphrase: "Enter or paste your text here...",
    paraphraseButton: "Paraphrase",
    paraphrasedOutput: "Your paraphrased text will appear here...",
    modeStandard: "Standard",
    modeFluent: "Fluent",
    modeFormal: "Formal",
    modeSimple: "Simple",
    modeCreative: "Creative",
    // Content Creator
    contentCreatorTitle: "AI Content Creator",
    contentCreatorDescription: "Create blogs, articles, emails, and more with ease. Just provide a topic, type, and tone.",
    enterTopic: "Enter a topic or a brief description...",
    contentType: "Content Type",
    tone: "Tone",
    generateContentButton: "Generate Content",
    generatedContentOutput: "Your generated content will appear here...",
    // AI Humanizer & Rewriter Modes
    humanizerTitle: "AI Text Humanizer",
    humanizerDescription: "Transform robotic AI-generated text into natural, human-like writing.",
    enterAIText: "Enter or paste your AI-generated text here...",
    humanizedOutput: "Your rewritten text will appear here...",
    modeAcademic: "Academic",
    modeExpand: "Expand",
    modeShorten: "Shorten",
    modeHumanize: "Humanize",
    modeFormalDesc: "Rephrases text in a more sophisticated way",
    modeSimpleDesc: "Presents text in a way that’s easy to understand",
    modeCreativeDesc: "Rephrases text in an original and innovative way",
    modeAcademicDesc: "Expresses text in a technical and scholarly way",
    modeExpandDesc: "Increases the length of text",
    modeShortenDesc: "Conveys meaning more concisely",
    modeHumanizeDesc: "Rewrites text in a more human, authentic way",
    // Data Analysis
    dataAnalysisTitle: "Data Analyzer",
    dataAnalysisDescription: "Upload a document to gain insights. The AI will generate visualizations, infographics, and flow charts.",
    dataUploadPrompt: "Upload a PDF, CSV, or TXT document to begin analysis.",
    extractingText: "Extracting text from document...",
    analysisOutputVisualization: "Data Visualization",
    analysisOutputVisualizationDesc: "Generate charts like bar, line, and pie graphs from your data.",
    analysisOutputInfographic: "Infographic",
    analysisOutputInfographicDesc: "Summarize key data points into a visually engaging infographic.",
    analysisOutputFlowChart: "Flow Chart",
    analysisOutputFlowChartDesc: "Identify and map out processes or workflows from your document.",
    generatingOutput: "Generating {outputType}...",
    exportPNG: "Export as PNG",
    exportSVG: "Export as SVG",
    resetAndAnalyzeNew: "Reset & Analyze New File",
    backToSelection: "Back to Selection",
    infographicGridView: "Grid View",
    infographicListView: "List View",
    infographicFocusView: "Focus View",
    previous: "Previous",
    next: "Next",
    // Presentation Generator
    presentationGeneratorTitle: "AI Presentation Generator",
    presentationGeneratorDescription: "Create stunning presentations in minutes in a dynamic, single-page workspace.",
    presentationStep1: "1. Choose Language",
    presentationStep2: "2. Define Content",
    presentationStep3: "3. Select Theme",
    presentationStep4: "4. Download",
    presentationTextAmount: "Amount of text per card",
    textAmountMinimal: "Minimal",
    textAmountConcise: "Concise",
    textAmountDetailed: "Detailed",
    textAmountExtensive: "Extensive",
    methodFromPrompt: "From Prompt",
    methodFromText: "From Text",
    methodFromFile: "From File",
    enterTopicPrompt: "Enter your presentation topic...",
    pasteTextPrompt: "Paste your content here...",
    importFilePrompt: "Upload a document (.pdf, .txt, .md)",
    slideCount: "Number of Slides",
    generateOutline: "Generate Outline",
    generatingOutline: "Generating Outline...",
    preview: "Preview",
    previewPlaceholder: "Your presentation preview will appear here once the outline is generated.",
    generateFullPresentation: "Generate Full Presentation",
    generatingFullPresentation: "Generating Full Presentation...",
    startOver: "Start Over",
    downloadAs: "Download As",
    downloadPDF: "PDF",
    downloadMarkdown: "Markdown",
    downloadPPTX: "PPTX",
    generatingPDF: "Generating PDF...",
    generatingPPTX: "Generating PPTX...",
    presentationListenNotes: "Listen to Notes",
    // Infographic Video Generator
    videoGenTitle: "Infographic Video Generator",
    videoGenDescription: "Watch your static documents change into bright videos that catch every eye.",
    videoGenBadge: "AI Video Creation",
    videoGenInputPlaceholder: "Paste your text here, or attach a document below...",
    videoGenOptionsTitle: "Video Options",
    videoGenDuration: "Duration",
    videoGenVoice: "Voice",
    videoGenOrientation: "Orientation",
    videoGenStyle: "Style",
    videoGenGenerateButton: "Generate Infographic Video",
    videoGenLoaderAnalyzing: "Analyzing document and creating video script...",
    videoGenLoaderGeneratingAssets: "Generating visuals & voiceover for {sceneCount} scenes...",
    videoGenLoaderProcessingScene: "Processing scene {currentScene} of {totalScenes}: '{sceneTitle}'",
    videoGenLoaderCalculatingDurations: "Finalizing scenes and calculating durations...",
    videoGenDownloadAssets: "Download Assets (.zip)",
    videoGenNewVideo: "New Video",
    videoGenScene: "Scene",
    // Admin
    adminTitle: "Admin Dashboard",
    adminOverview: "Overview",
    adminUsers: "Users",
    adminSettings: "Settings",
    adminStatsTotalUsers: "Total Users",
    adminStatsRevenue: "Revenue",
    adminStatsActiveSessions: "Active Sessions",
    adminTableName: "Name",
    adminTableEmail: "Email",
    adminTableRole: "Role",
    adminTableStatus: "Status",
    adminTableActions: "Actions",
    adminUserSearch: "Search users...",
    // General
    apiKeyError: "No API key is configured. Please check your env.js file and add at least one API key to use the services.",
    apiKeyErrorForModel: "API Key for {modelName} is not configured. Please add it to env.js to use this model.",
    errorOccurred: "An error occurred. Please try again.",
    connectWithUs: "Connect with us",
    history: "History",
    clearHistory: "Clear History",
    noHistory: "No history yet.",
    premiumFeature: "Premium",
    serviceComingSoon: "Coming Soon",
    // Auth
    loginRegister: "Login",
    login: "Login",
    register: "Register",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    signInWithGoogle: "Sign in with Google",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    createAccount: "Create Account",
    logout: "Logout",
    registrationSuccess: "Registration successful! Please log in.",
    errorPasswordMismatch: "Passwords do not match.",
    errorPasswordLength: "Password must be at least 8 characters.",
    errorInvalidEmail: "Please enter a valid email address.",
    errorFullNameRequired: "Full Name is required.",
    errorUserExists: "A user with this email already exists.",
    errorInvalidCredentials: "Invalid email or password.",
    authRequiredTitle: "Authentication Required",
    authRequiredMessage: "Access Restricted. Please create a free account to continue. For full access, consider upgrading to a Premium plan.",
    upgradeRequiredTitle: "Upgrade to Premium to Unlock",
    upgradeRequiredMessage: "This is a premium feature. Please upgrade your plan to get full access and boost your productivity.",
    viewPlans: "View Plans",
    noCreditCardRequired: "No credit card required",
    authRegistrationDisclaimer_p1: "By creating an account, you agree to our",
    authRegistrationDisclaimer_terms: "Terms & Conditions",
    authRegistrationDisclaimer_p2: "and acknowledge you have read our",
    authRegistrationDisclaimer_privacy: "Privacy Policy",
    authRegistrationDisclaimer_p3: ".",
  },
  [Language.AR]: {
    title: "عبقري العلوم",
    navHome: "الرئيسية",
    navServices: "الخدمات",
    navAbout: "من نحن",
    navContact: "اتصل بنا",
    navPricing: "الأسعار والخطط",
    navSupport: "الدعم",
    navTerms: "الشروط والأحكام",
    navPrivacy: "أمان وخصوصية البيانات",
    navAdmin: "لوحة تحكم المسؤول",
    navResearch: "مساعد البحث العلمي",
    navResearchWriter: "كاتب الأبحاث الذكي",
    navPrompt: "مولد الأوامر",
    navDesign: "مصمم الديكور الداخلي",
    navTranslator: "المترجم الذكي",
    navParaphraser: "معيد الصياغة الذكي",
    navContentCreator: "صانع المحتوى",
    navAIHumanizer: "أنسنة النص الذكي",
    navDataAnalysis: "محلل البيانات",
    navPresentationGenerator: "مولد العروض التقديمية",
    navInfographicVideo: "مولد فيديو إنفوجرافيك",
    navSciGeniusChat: "تحدث مع عبقري العلوم",
    // Home
    homeWelcome: "مرحباً، أنا عبقري العلوم",
    homeDescription: "مساعدك الذكي متعدد المهام. كيف يمكنني مساعدتك اليوم؟",
    homeCardResearchTitle: "مساعد البحث الأكاديمي",
    homeCardResearchDesc: "ارفع الأوراق البحثية وتحدث مع الذكاء الاصطناعي للحصول على ملخصات ورؤى ودراسات ذات صلة",
    homeCardPromptTitle: "مولد الأوامر",
    homeCardPromptDesc: "حول الأفكار البسيطة إلى مطالبات مفصلة وموحية لتوليد الصور والنصوص بالذكاء الاصطناعي",
    homeCardDesignTitle: "مصمم الديكور الداخلي",
    homeCardDesignDesc: "ارفع صورة غرفة ودع الذكاء الاصطناعي يعيد تصميمها بأسلوبك المختار",
    homeCardTranslatorTitle: "المترجم الذكي",
    homeCardTranslatorDesc: "ترجم النصوص بذكاء اصطناعي يدرك السياق للحصول على نتائج دقيقة.",
    homeCardParaphraserTitle: "معيد الصياغة الذكي",
    homeCardParaphraserDesc: "أعد كتابة نصوصك بنبرات وأساليب مختلفة لتحسين الوضوح والتأثير",
    homeCardContentCreatorTitle: "صانع المحتوى",
    homeCardContentCreatorDesc: "أنشئ مدونات ومقالات ورسائل بريد إلكتروني بسهولة عبر تحديد الموضوع والنوع والنبرة.",
    homeCardResearchWriterTitle: "كاتب الأبحاث الذكي",
    homeCardResearchWriterDesc: "صياغة الأوراق الأكاديمية والمقترحات ومراجعات الأدبيات بمساعدة الذكاء الاصطناعي.",
    homeCardAIHumanizerTitle: "أنسنة النص الذكي",
    homeCardAIHumanizerDesc: "أعد كتابة النص الذي تم إنشاؤه بواسطة الذكاء الاصطناعي ليبدو أكثر طبيعية وأقل آلية.",
    homeCardDataAnalysisTitle: "محلل البيانات",
    homeCardDataAnalysisDesc: "حلل البيانات من المستندات لإنشاء مخططات ورسوم بيانية معلوماتية ومخططات تدفق.",
    homeCardPresentationGeneratorTitle: "مساعد العروض التقديمية",
    homeCardPresentationGeneratorDesc: "أنشئ مخططات تفصيلية لعروض تقديمية بناءً على موضوعك وأهدافك.",
    homeCardInfographicVideoTitle: "مولد فيديو إنفوجرافيك",
    homeCardInfographicVideoDesc: "حوّل النصوص الثابتة من المستندات إلى فيديوهات إنفوجرافيك ديناميكية وجذابة.",
    homeCardSciGeniusChatTitle: "تحدث مع عبقري العلوم",
    homeCardSciGeniusChatDesc: "أجرِ محادثة، اطرح أسئلة، أرفق ملفات، وابحث في الويب.",
    showMore: "عرض المزيد",
    showLess: "عرض الأقل",
    // Welcome Modal
    welcomeTitle: "مرحباً بك في عبقري العلوم",
    welcomeDescription: "منصتك الشاملة للبحث والإبداع والتصميم بالذكاء الاصطناعي. لنبدأ الآن!",
    welcomeStart: "ابدأ الآن",
    welcomeAuth: "تسجيل الدخول / إنشاء حساب",
    // About Us
    aboutTitle: "عن عبقري العلوم",
    aboutVisionTitle: "رؤيتنا",
    aboutVisionText: "إضفاء الطابع الديمقراطي على قوة الذكاء الاصطناعي، وتحويل التكنولوجيا المعقدة إلى أداة بسيطة وبديهية تعزز الإبداع البشري والبراعة.",
    aboutMissionTitle: "مهمتنا",
    aboutMissionText: "نسعى جاهدين لتمكين المستخدمين من تحويل أفكارهم ونصوصهم العادية إلى أوامر احترافية ومصقولة تستفيد بشكل كامل من إمكانيات الذكاء الاصطناعي.",
    aboutValuesTitle: "قيمنا",
    aboutValuePrivacy: "الخصوصية",
    aboutValuePrivacyDesc: "الالتزام بحماية بيانات المستخدم وضمان سريتها.",
    aboutValueTransparency: "الشفافية",
    aboutValueTransparencyDesc: "الوضوح في كيفية عمل الذكاء الاصطناعي لدينا والبيانات التي يستخدمها.",
    aboutValueImprovement: "التحسين",
    aboutValueImprovementDesc: "التحسين المستمر لأدواتنا من أجل تفاعل أفضل مع الذكاء الاصطناعي.",
    aboutStoryTitle: "قصتنا",
    aboutStoryText: "بدأت قصتنا برؤية لجعل الذكاء الاصطناعي في متناول الجميع. لقد أنشأنا أداة متقدمة تحول النصوص العادية إلى أوامر احترافية، مما يبسط المهام ويحقق نتائج رائعة.",
    // Contact Us
    contactTitle: "تواصل معنا",
    contactDescription: "هل لديك سؤال أو تود الدردشة؟ نحن هنا للمساعدة. تواصل معنا عبر إحدى القنوات أدناه.",
    contactEmailTitle: "راسلنا عبر البريد الإلكتروني",
    contactEmailDescription: "للدعم أو الشراكات أو الاستفسارات الأخرى.",
    contactEmailAddress: "roadmap.casa@gmail.com",
    contactTelegramTitle: "انضم إلى تليجرام",
    contactTelegramDescription: "اطرح الأسئلة وتفاعل مع المجتمع.",
    contactTelegramHandle: "انضم للقناة",
    // Pricing
    pricingTitle: "اختر خطتك",
    pricingDescription: "أطلق العنان للقوة الكاملة لعبقري العلوم وعزز إنتاجيتك. اختر الخطة المناسبة لك.",
    monthly: "شهرياً",
    yearly: "سنوياً",
    save20: "وفر 20%",
    mostPopular: "الأكثر شيوعاً",
    choosePlan: "اختر الخطة",
    getStarted: "ابدأ الآن",
    limitedTimeOffer: "عرض لفترة محدودة - خصم ٥٠٪",
    originally: "السعر الأصلي",
    // Payment Modal
    paymentTitle: "أكمل عملية الشراء",
    paymentFor: "أنت على وشك الاشتراك في",
    cardNumber: "رقم البطاقة",
    expiryDate: "تاريخ انتهاء الصلاحية (MM/YY)",
    cvc: "CVC",
    payNow: "ادفع الآن",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تم الدفع بنجاح!",
    welcomeAboard: "أهلاً بك! لديك الآن وصول كامل إلى عبقري العلوم.",
    // Research
    researchTitle: "مساعد البحث العلمي",
    researchDescription: "قم برفع مستند لبدء محادثة، أو اطلب مني البحث عن أوراق بحثية ذات صلة.",
    uploadArea: "اسحب وأفلت ملفًا هنا، أو انقر للاختيار",
    uploading: "جاري الرفع...",
    fileReady: "جاهز. اسألني أي شيء عنه.",
    askPlaceholder: "اطرح سؤالاً...",
    suggestion1: "لخص الملخص",
    suggestion2: "ما هي النتائج الرئيسية؟",
    suggestion3: "ابحث عن أوراق بحثية ذات صلة",
    thinking: "عبقري العلوم يفكر...",
    sources: "المصادر",
    relatedPapers: "أوراق بحثية ذات صلة",
    // SciGenius Chat
    chatTitle: "تحدث مع عبقري العلوم",
    chatDescription: "مساعدك الشخصي الذكي. اسألني أي شيء، أرفق ملفات، أو ابحث في الويب عن أحدث المعلومات.",
    searchWeb: "البحث في الويب",
    attachFile: "إرفاق ملف",
    // Research Writer
    researchWriterTitle: "كاتب الأبحاث بالذكاء الاصطناعي",
    researchWriterDescription: "اختر قالبًا للبدء في كتابتك الأكاديمية. سيساعدك الذكاء الاصطناعي لدينا على صياغة محتوى جيد التنظيم ومقنع.",
    researchProposalTitle: "مقترح بحثي",
    researchProposalDesc: "صياغة مقترح بحثي مقنع بهيكل واضح، من المقدمة إلى المنهجية.",
    literatureReviewTitle: "مراجعة الأدبيات",
    literatureReviewDesc: "إنشاء مراجعة أدبيات نقدية وشاملة لورقتك البحثية أو رسالتك العلمية.",
    abstractWritingTitle: "كتابة الملخص",
    abstractWritingDesc: "كتابة ملخص قوي وموجز لمشروعك البحثي الأكاديمي، مصمم خصيصًا لاحتياجاتك.",
    thesisStatementTitle: "صياغة الأطروحة",
    thesisStatementDesc: "تطوير صياغة أطروحة قوية وواضحة تجعل مقالتك أو ورقتك البحثية متميزة.",
    essayWritingTitle: "كتابة المقال",
    essayWritingDesc: "تبسيط عملية كتابة المقالات بمساعدة الذكاء الاصطناعي خطوة بخطوة، من المخطط التفصيلي إلى الخاتمة.",
    backToTemplates: "العودة إلى القوالب",
    enterTopicFor: "أدخل موضوعك أو نقاطك الرئيسية أو مسودتك لـ",
    generate: "إنشاء",
    generating: "جاري الإنشاء...",
    // Prompt
    promptTitle: "مولد الأوامر",
    promptDescription: "قدم فكرة بسيطة، وسأقوم بتوسيعها إلى موجه مفصل ومثير للذكاء الاصطناعي التوليدي.",
    promptPlaceholder: "مثال: منظر مدينة مستقبلية عند غروب الشمس",
    generateSimplePrompt: "موجه بسيط",
    generateAdvancedPrompt: "موجه متقدم",
    generateImagePrompt: "موجه صورة",
    generateVideoPrompt: "موجه فيديو",
    copy: "نسخ",
    copied: "تم النسخ!",
    tabGenerate: "إنشاء موجه",
    tabCheck: "فحص موجه",
    promptCheckerTitle: "مدقق الأوامر الذكي",
    promptCheckerDescription: "حلل وقيم وحسن أوامرك الحالية للحصول على نتائج أفضل من الذكاء الاصطناعي.",
    enterPromptToCheck: "أدخل أو الصق موجهك هنا لتحليله...",
    checkPromptButton: "تحليل الموجه",
    checkingPrompt: "جاري التحليل...",
    analysisTitle: "تحليل الموجه",
    errorsTitle: "المشاكل المكتشفة",
    qualityLevelTitle: "مستوى الجودة",
    enhancedPromptTitle: "الموجه المحسن",
    // Design
    designTitle: "مصمم الديكور الداخلي بالذكاء الاصطناعي",
    designDescription: "أعد تصور مساحتك. ارفع صورة، اختر نوع الغرفة والنمط، ودع الذكاء الاصطناعي يقوم بالباقي.",
    step1: "١. ارفع صورة",
    step2: "٢. اختر نوع الغرفة",
    step3: "٣. اختر النمط",
    selectRoomType: "اختر نوع الغرفة",
    roomTypes: { living: "غرفة معيشة", bedroom: "غرفة نوم", kitchen: "مطبخ", office: "مكتب", dining: "غرفة طعام", bathroom: "حمام" },
    redesign: "أعد تصميم الغرفة",
    redesigning: "جاري إعادة تصميم غرفتك... قد يستغرق هذا بعض الوقت.",
    before: "قبل",
    after: "بعد",
    aiDescription: "وصف الذكاء الاصطناعي",
    download: "تحميل التصميم",
    // Translator
    translatorTitle: "مترجم يعمل بالذكاء الاصطناعي",
    translatorDescription: "ترجم النصوص بذكاء اصطناعي يدرك السياق للحصول على نتائج دقيقة.",
    sourceLanguage: "لغة المصدر",
    targetLanguage: "اللغة الهدف",
    enterText: "أدخل النص للترجمة...",
    translate: "ترجم",
    translating: "جاري الترجمة...",
    confidenceScore: "مستوى الثقة",
    listen: "استمع",
    documentTranslation: "ترجمة المستندات",
    uploadTxt: "ارفع ملف .txt, .md, .pdf أو صورة",
    simulatedModel: "نموذج الذكاء الاصطناعي المحاكى",
    quickPhrases: "عبارات سريعة",
     // Paraphraser
    paraphraserTitle: "معيد الصياغة الذكي",
    paraphraserDescription: "أعد كتابة نصوصك. اختر وضعًا لضبط النبرة والأسلوب ليناسب أي مناسبة.",
    enterTextToParaphrase: "أدخل أو الصق نصك هنا...",
    paraphraseButton: "إعادة صياغة",
    paraphrasedOutput: "سيظهر النص المعاد صياغته هنا...",
    modeStandard: "قياسي",
    modeFluent: "سلس",
    modeFormal: "رسمي",
    modeSimple: "بسيط",
    modeCreative: "إبداعي",
    // Content Creator
    contentCreatorTitle: "صانع المحتوى بالذكاء الاصطناعي",
    contentCreatorDescription: "أنشئ مدونات ومقالات ورسائل بريد إلكتروني بسهولة. فقط قدم موضوعًا ونوعًا ونبرة.",
    enterTopic: "أدخل موضوعًا أو وصفًا موجزًا...",
    contentType: "نوع المحتوى",
    tone: "النبرة",
    generateContentButton: "إنشاء محتوى",
    generatedContentOutput: "سيظهر المحتوى الذي تم إنشاؤه هنا...",
    // AI Humanizer & Rewriter Modes
    humanizerTitle: "أنسنة النص بالذكاء الاصطناعي",
    humanizerDescription: "حوّل نصوص الذكاء الاصطناعي الآلية إلى كتابة طبيعية شبيهة بالكتابة البشرية.",
    enterAIText: "أدخل أو الصق النص الذي تم إنشاؤه بواسطة الذكاء الاصطناعي هنا...",
    humanizedOutput: "سيظهر النص المعاد كتابته هنا...",
    modeAcademic: "أكاديمي",
    modeExpand: "توسيع",
    modeShorten: "تقصير",
    modeHumanize: "أنسنة",
    modeFormalDesc: "يعيد صياغة النص بطريقة أكثر تطوراً",
    modeSimpleDesc: "يقدم النص بطريقة سهلة الفهم",
    modeCreativeDesc: "يعيد صياغة النص بطريقة أصلية ومبتكرة",
    modeAcademicDesc: "يعبر عن النص بطريقة تقنية وعلمية",
    modeExpandDesc: "يزيد من طول النص",
    modeShortenDesc: "ينقل المعنى بإيجاز أكبر",
    modeHumanizeDesc: "يعيد كتابة النص بطريقة أكثر إنسانية وأصالة",
    // Data Analysis
    dataAnalysisTitle: "محلل البيانات",
    dataAnalysisDescription: "ارفع مستندًا للحصول على رؤى. سيقوم الذكاء الاصطناعي بإنشاء تصورات ورسوم بيانية معلوماتية ومخططات تدفق.",
    dataUploadPrompt: "ارفع مستند PDF أو CSV أو TXT لبدء التحليل.",
    extractingText: "جاري استخلاص النص من المستند...",
    analysisOutputVisualization: "تصور البيانات",
    analysisOutputVisualizationDesc: "أنشئ مخططات مثل الأعمدة والخطوط والدوائر من بياناتك.",
    analysisOutputInfographic: "رسم بياني معلوماتي",
    analysisOutputInfographicDesc: "لخص نقاط البيانات الرئيسية في رسم معلوماتي جذاب بصريًا.",
    analysisOutputFlowChart: "مخطط تدفقي",
    analysisOutputFlowChartDesc: "حدد العمليات أو التسلسلات من مستندك وقم برسمها.",
    generatingOutput: "جاري إنشاء {outputType}...",
    exportPNG: "تصدير كـ PNG",
    exportSVG: "تصدير كـ SVG",
    resetAndAnalyzeNew: "إعادة تعيين وتحليل ملف جديد",
    backToSelection: "العودة للاختيار",
    infographicGridView: "عرض شبكي",
    infographicListView: "عرض قائمة",
    infographicFocusView: "عرض مركّز",
    previous: "السابق",
    next: "التالي",
    // Presentation Generator
    presentationGeneratorTitle: "مولد العروض التقديمية بالذكاء الاصطناعي",
    presentationGeneratorDescription: "أنشئ عروضًا تقديمية مذهلة في دقائق في مساحة عمل ديناميكية بصفحة واحدة.",
    presentationStep1: "١. اختر اللغة",
    presentationStep2: "٢. حدد المحتوى",
    presentationStep3: "٣. اختر القالب",
    presentationStep4: "٤. تحميل",
    presentationTextAmount: "كمية النص لكل شريحة",
    textAmountMinimal: "قليل جداً",
    textAmountConcise: "مختصر",
    textAmountDetailed: "مفصل",
    textAmountExtensive: "موسع",
    methodFromPrompt: "من فكرة",
    methodFromText: "من نص",
    methodFromFile: "من ملف",
    enterTopicPrompt: "أدخل موضوع العرض التقديمي...",
    pasteTextPrompt: "الصق المحتوى الخاص بك هنا...",
    importFilePrompt: "ارفع مستندًا (.pdf, .txt, .md)",
    slideCount: "عدد الشرائح",
    generateOutline: "إنشاء المخطط",
    generatingOutline: "جاري إنشاء المخطط...",
    preview: "معاينة",
    previewPlaceholder: "ستظهر معاينة عرضك التقديمي هنا بمجرد إنشاء المخطط.",
    generateFullPresentation: "إنشاء العرض الكامل",
    generatingFullPresentation: "جاري إنشاء العرض الكامل...",
    startOver: "البدء من جديد",
    downloadAs: "تحميل كـ",
    downloadPDF: "PDF",
    downloadMarkdown: "Markdown",
    downloadPPTX: "PPTX",
    generatingPDF: "جاري إنشاء PDF...",
    generatingPPTX: "جاري إنشاء PPTX...",
    presentationListenNotes: "الاستماع إلى الملاحظات",
    // Infographic Video Generator
    videoGenTitle: "مولد فيديو إنفوجرافيك",
    videoGenDescription: "شاهد مستنداتك الثابتة تتحول إلى فيديوهات ساطعة تخطف كل الأنظار.",
    videoGenBadge: "إنشاء فيديو بالذكاء الاصطناعي",
    videoGenInputPlaceholder: "الصق النص هنا، أو أرفق مستندًا أدناه...",
    videoGenOptionsTitle: "خيارات الفيديو",
    videoGenDuration: "المدة",
    videoGenVoice: "الصوت",
    videoGenOrientation: "الاتجاه",
    videoGenStyle: "النمط",
    videoGenGenerateButton: "إنشاء فيديو إنفوجرافيك",
    videoGenLoaderAnalyzing: "جاري تحليل المستند وإنشاء سيناريو الفيديو...",
    videoGenLoaderGeneratingAssets: "جاري إنشاء الصور والتعليق الصوتي لـ {sceneCount} مشاهد...",
    videoGenLoaderProcessingScene: "معالجة المشهد {currentScene} من {totalScenes}: '{sceneTitle}'",
    videoGenLoaderCalculatingDurations: "وضع اللمسات الأخيرة على المشاهد وحساب المدد الزمنية...",
    videoGenDownloadAssets: "تحميل المكونات (.zip)",
    videoGenNewVideo: "فيديو جديد",
    videoGenScene: "مشهد",
    // Admin
    adminTitle: "لوحة تحكم المسؤول",
    adminOverview: "نظرة عامة",
    adminUsers: "المستخدمين",
    adminSettings: "الإعدادات",
    adminStatsTotalUsers: "إجمالي المستخدمين",
    adminStatsRevenue: "الإيرادات",
    adminStatsActiveSessions: "الجلسات النشطة",
    adminTableName: "الاسم",
    adminTableEmail: "البريد الإلكتروني",
    adminTableRole: "الدور",
    adminTableStatus: "الحالة",
    adminTableActions: "الإجراءات",
    adminUserSearch: "بحث عن مستخدمين...",
    // General
    apiKeyError: "لم يتم تكوين أي مفتاح API. يرجى التحقق من ملف env.js وإضافة مفتاح API واحد على الأقل لاستخدام الخدمات.",
    apiKeyErrorForModel: "مفتاح API لـ {modelName} غير مكون. يرجى إضافته إلى env.js لاستخدام هذا النموذج.",
    errorOccurred: "حدث خطأ. يرجى المحاولة مرة أخرى.",
    connectWithUs: "تواصل معنا",
    history: "السجل",
    clearHistory: "مسح السجل",
    noHistory: "لا يوجد سجل حتى الآن.",
    premiumFeature: "بريميوم",
    serviceComingSoon: "قريباً",
    // Auth
    loginRegister: "تسجيل الدخول",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    signInWithGoogle: "تسجيل الدخول باستخدام جوجل",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    createAccount: "إنشاء حساب",
    logout: "تسجيل الخروج",
    registrationSuccess: "تم التسجيل بنجاح! يرجى تسجيل الدخول.",
    errorPasswordMismatch: "كلمتا المرور غير متطابقتين.",
    errorPasswordLength: "يجب أن تكون كلمة المرور ٨ أحرف على الأقل.",
    errorInvalidEmail: "يرجى إدخال عنوان بريد إلكتروني صالح.",
    errorFullNameRequired: "الاسم الكامل مطلوب.",
    errorUserExists: "يوجد مستخدم بهذا البريد الإلكتروني بالفعل.",
    errorInvalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صالحة.",
    authRequiredTitle: "تسجيل الدخول مطلوب",
    authRequiredMessage: "الوصول مقيد. يرجى إنشاء حساب مجاني للمتابعة. للحصول على وصول كامل، ضع في اعتبارك الترقية إلى خطة مدفوعة.",
    upgradeRequiredTitle: "قم بالترقية إلى بريميوم لفتح الميزة",
    upgradeRequiredMessage: "هذه ميزة مدفوعة. يرجى ترقية خطتك للحصول على وصول كامل وتعزيز إنتاجيتك.",
    viewPlans: "عرض الخطط",
    noCreditCardRequired: "لا حاجة لبطاقة ائتمان",
    authRegistrationDisclaimer_p1: "بإنشاء حساب، فإنك توافق على",
    authRegistrationDisclaimer_terms: "الشروط والأحكام",
    authRegistrationDisclaimer_p2: "وتقر بأنك قد قرأت",
    authRegistrationDisclaimer_privacy: "سياسة الخصوصية",
    authRegistrationDisclaimer_p3: "الخاصة بنا.",
  },
};

export const PRICING_PLANS = [
  {
    id: 'free',
    name: { en: 'Free', ar: 'مجاني' },
    isPopular: false,
    monthly: {
      price: { en: '$0', ar: '٠$' },
      period: { en: '/month', ar: '/شهر' },
    },
    features: [
      { en: '50 monthly credits', ar: '٥٠ رصيد شهري' },
      { en: 'Speak with SciGenius (Limited)', ar: 'تحدث مع عبقري العلوم (استخدام محدود)' },
      { en: 'Research Copilot (Limited)', ar: 'مساعد البحث (استخدام محدود)' },
      { en: 'Research Writer (Limited)', ar: 'كاتب الأبحاث (استخدام محدود)' },
      { en: 'Prompt Generator (Limited)', ar: 'مولد الأفكار (استخدام محدود)' },
      { en: 'AI Paraphraser (Limited)', ar: 'معيد الصياغة (استخدام محدود)' },
      { en: 'Content Creator (Limited)', ar: 'صانع المحتوى (استخدام محدود)' },
      { en: 'AI Translator (Limited)', ar: 'المترجم (استخدام محدود)' },
      { en: 'Standard support', ar: 'دعم قياسي' },
    ],
    buttonTextKey: 'getStarted',
  },
  {
    id: 'premium',
    name: { en: 'Premium', ar: 'بريميوم' },
    isPopular: true,
    monthly: {
      price: { en: '$9.95', ar: '٩.٩٥$' },
      original_price: { en: '$19.90', ar: '١٩.٩٠$' },
      period: { en: '/month', ar: '/شهر' },
    },
    yearly: {
      price: { en: '$96', ar: '٩٦$' },
      period: { en: '/year', ar: '/سنة' },
    },
    features: [
      { en: '500 monthly credits (10x)', ar: '٥٠٠ رصيد شهري (10 أضعاف)' },
      { en: 'Data Analyzer (Unlimited)', ar: 'محلل البيانات (غير محدود)' },
      { en: 'AI Presentation Assistant (Unlimited)', ar: 'مساعد العروض التقديمية (غير محدود)' },
      { en: 'Infographic Video Generator (Unlimited)', ar: 'مولد فيديو إنفوجرافيك (غير محدود)' },
      { en: 'AI Interior Designer (Unlimited)', ar: 'مصمم الديكور (غير محدود)' },
      { en: 'AI Humanizer (Unlimited)', ar: 'أنسنة النص (غير محدود)' },
      { en: 'Speak with SciGenius (Unlimited)', ar: 'تحدث مع عبقري العلوم (غير محدود)' },
      { en: 'Research Copilot (Unlimited)', ar: 'مساعد البحث (غير محدود)' },
      { en: 'Research Writer (Unlimited)', ar: 'كاتب الأبحاث (غير محدود)' },
      { en: 'Prompt Generator (Unlimited)', ar: 'مولد الأفكار (غير محدود)' },
      { en: 'AI Paraphraser (Unlimited)', ar: 'معيد الصياغة (غير محدود)' },
      { en: 'Content Creator (Unlimited)', ar: 'صانع المحتوى (غير محدود)' },
      { en: 'AI Translator (Unlimited)', ar: 'المترجم (غير محدود)' },
      { en: 'Priority support', ar: 'دعم ذو أولوية' },
      { en: 'Early access to new features', ar: 'وصول مبكر للميزات الجديدة' },
    ],
    buttonTextKey: 'choosePlan',
  },
];


export const DESIGN_STYLES = [
  { id: 'Modern', name: (lang) => lang === Language.EN ? 'Modern' : 'حديث', imageUrl: 'https://picsum.photos/seed/modern/300/200' },
  { id: 'Minimalist', name: (lang) => lang === Language.EN ? 'Minimalist' : 'بسيط', imageUrl: 'https://picsum.photos/seed/minimalist/300/200' },
  { id: 'Bohemian', name: (lang) => lang === Language.EN ? 'Bohemian' : 'بوهيمي', imageUrl: 'https://picsum.photos/seed/bohemian/300/200' },
  { id: 'Industrial', name: (lang) => lang === Language.EN ? 'Industrial' : 'صناعي', imageUrl: 'https://picsum.photos/seed/industrial/300/200' },
  { id: 'Scandinavian', name: (lang) => lang === Language.EN ? 'Scandinavian' : 'اسكندنافي', imageUrl: 'https://picsum.photos/seed/scandinavian/300/200' },
  { id: 'Coastal', name: (lang) => lang === Language.EN ? 'Coastal' : 'ساحلي', imageUrl: 'https://picsum.photos/seed/coastal/300/200' },
];

export const PARAPHRASE_MODES = [
  { id: 'standard', name: (lang) => i18n[lang].modeStandard },
  { id: 'fluent', name: (lang) => i18n[lang].modeFluent },
  { id: 'formal', name: (lang) => i18n[lang].modeFormal },
  { id: 'simple', name: (lang) => i18n[lang].modeSimple },
  { id: 'creative', name: (lang) => i18n[lang].modeCreative },
];

export const RESEARCH_WRITER_TEMPLATES = [
  { id: 'research_proposal', title: (lang) => i18n[lang].researchProposalTitle, description: (lang) => i18n[lang].researchProposalDesc },
  { id: 'literature_review', title: (lang) => i18n[lang].literatureReviewTitle, description: (lang) => i18n[lang].literatureReviewDesc },
  { id: 'abstract_writing', title: (lang) => i18n[lang].abstractWritingTitle, description: (lang) => i18n[lang].abstractWritingDesc },
  { id: 'thesis_statement', title: (lang) => i18n[lang].thesisStatementTitle, description: (lang) => i18n[lang].thesisStatementDesc },
  { id: 'essay_writing', title: (lang) => i18n[lang].essayWritingTitle, description: (lang) => i18n[lang].essayWritingDesc },
];

export const HUMANIZE_MODES = [
  { id: 'formal', name: (lang) => i18n[lang].modeFormal, description: (lang) => i18n[lang].modeFormalDesc },
  { id: 'simple', name: (lang) => i18n[lang].modeSimple, description: (lang) => i18n[lang].modeSimpleDesc },
  { id: 'creative', name: (lang) => i18n[lang].modeCreative, description: (lang) => i18n[lang].modeCreativeDesc },
  { id: 'academic', name: (lang) => i18n[lang].modeAcademic, description: (lang) => i18n[lang].modeAcademicDesc },
  { id: 'expand', name: (lang) => i18n[lang].modeExpand, description: (lang) => i18n[lang].modeExpandDesc },
  { id: 'shorten', name: (lang) => i18n[lang].modeShorten, description: (lang) => i18n[lang].modeShortenDesc },
  { id: 'humanize', name: (lang) => i18n[lang].modeHumanize, description: (lang) => i18n[lang].modeHumanizeDesc },
];

export const DATA_ANALYSIS_OUTPUT_TYPES = [
    { id: 'visualization', nameKey: 'analysisOutputVisualization', descKey: 'analysisOutputVisualizationDesc', icon: DataAnalysisIcon },
    { id: 'infographic', nameKey: 'analysisOutputInfographic', descKey: 'analysisOutputInfographicDesc', icon: InfographicIcon },
    { id: 'flowchart', nameKey: 'analysisOutputFlowChart', descKey: 'analysisOutputFlowChartDesc', icon: FlowChartIcon },
];

export const PRESENTATION_TEXT_AMOUNTS = [
  { id: 'minimal', nameKey: 'textAmountMinimal' },
  { id: 'concise', nameKey: 'textAmountConcise' },
  { id: 'detailed', nameKey: 'textAmountDetailed' },
  { id: 'extensive', nameKey: 'textAmountExtensive' },
];

export const PRESENTATION_LANGUAGES = [
  { code: 'en', name: 'English', arName: 'الإنجليزية' },
  { code: 'ar', name: 'Arabic', arName: 'العربية' },
  { code: 'zh', name: 'Chinese', arName: 'الصينية' },
  { code: 'fr', name: 'French', arName: 'الفرنسية' },
  { code: 'de', name: 'German', arName: 'الألمانية' },
  { code: 'ru', name: 'Russian', arName: 'الروسية' },
];

export const PRESENTATION_THEMES = [
  // Dark Themes
  {
    id: 'midnight_bloom',
    name: { en: 'Midnight Bloom', ar: 'زهرة منتصف الليل' },
    colors: {
      previewBg: '#1a1829',
      slideBg: 'linear-gradient(145deg, #2c234b 0%, #161425 100%)',
      cardBg: 'rgba(255, 255, 255, 0.05)',
      title: '#e845a2',
      body: '#d0c2ff',
      accent: '#7df9ff',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'cyberpunk_glow',
    name: { en: 'Cyber Glow', ar: 'وهج سيبراني' },
    colors: {
      previewBg: '#0d0d0d',
      slideBg: 'linear-gradient(to right, #141e30, #243b55)',
      cardBg: 'rgba(0, 0, 0, 0.2)',
      title: '#39ff14',
      body: '#cccccc',
      accent: '#f70fff',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'obsidian',
    name: { en: 'Obsidian', ar: 'سبج' },
    colors: {
      previewBg: '#111',
      slideBg: 'linear-gradient(135deg, #222 0%, #000 100%)',
      cardBg: 'rgba(255, 255, 255, 0.03)',
      title: '#ffffff',
      body: '#bbbbbb',
      accent: '#ff4b1f',
    },
    fonts: { title: "'Roboto Slab', serif", body: "'Poppins', sans-serif" },
  },
  {
    id: 'forest_night',
    name: { en: 'Forest Night', ar: 'ليل الغابة' },
    colors: {
      previewBg: '#1E2D2B',
      slideBg: 'linear-gradient(to top, #09203f 0%, #537895 100%)',
      cardBg: 'rgba(255, 255, 255, 0.05)',
      title: '#a8ff78',
      body: '#e0e0e0',
      accent: '#78ffd6',
    },
    fonts: { title: "'Merriweather', serif", body: "'Lato', sans-serif" },
  },
   {
    id: 'deep_space',
    name: { en: 'Deep Space', ar: 'الفضاء العميق' },
    colors: {
      previewBg: '#000000',
      slideBg: 'linear-gradient(to right, #000000, #434343)',
      cardBg: 'rgba(255, 255, 255, 0.05)',
      title: '#FFFFFF',
      body: '#E0E0E0',
      accent: '#00D1FF',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Poppins', sans-serif" },
  },
  {
    id: 'royal_velvet',
    name: { en: 'Royal Velvet', ar: 'المخمل الملكي' },
    colors: {
      previewBg: '#2A0A4A',
      slideBg: 'linear-gradient(135deg, #3C1053 0%, #AD5389 100%)',
      cardBg: 'rgba(255, 255, 255, 0.08)',
      title: '#FFD700',
      body: '#F5DEB3',
      accent: '#DA70D6',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Lato', sans-serif" },
  },
  // Light Themes
  {
    id: 'parchment',
    name: { en: 'Parchment', ar: 'رق' },
    colors: {
      previewBg: '#e9e4d9',
      slideBg: 'linear-gradient(145deg, #FAF8F0 0%, #E9E4D9 100%)',
      cardBg: 'rgba(255, 255, 255, 0.5)',
      title: '#4a5c55',
      body: '#5e6b65',
      accent: '#9a6b5d',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'zephyr',
    name: { en: 'Zephyr', ar: 'نسيم' },
    colors: {
      previewBg: '#e0f2fe',
      slideBg: 'linear-gradient(to bottom, #ffffff, #e0f7fa)',
      cardBg: 'rgba(255, 255, 255, 0.7)',
      title: '#0c4a6e',
      body: '#374151',
      accent: '#0ea5e9',
    },
    fonts: { title: "'Merriweather', serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'mint_fresh',
    name: { en: 'Mint Fresh', ar: 'نعناع منعش' },
    colors: {
      previewBg: '#F0FFF4',
      slideBg: 'linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%)',
      cardBg: 'rgba(255, 255, 255, 0.6)',
      title: '#2F4F4F',
      body: '#3E563E',
      accent: '#20B2AA',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'sakura',
    name: { en: 'Sakura', ar: 'ساكورا' },
    colors: {
      previewBg: '#FFF0F5',
      slideBg: 'linear-gradient(to top, #fff1eb 0%, #ace0f9 100%)',
      cardBg: 'rgba(255, 255, 255, 0.7)',
      title: '#C71585',
      body: '#4B0082',
      accent: '#FF69B4',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Poppins', sans-serif" },
  },
  {
    id: 'sandstone',
    name: { en: 'Sandstone', ar: 'حجر رملي' },
    colors: {
      previewBg: '#FDF6E3',
      slideBg: 'linear-gradient(to right, #f8f2d6, #fdf5e6)',
      cardBg: 'rgba(255, 255, 255, 0.5)',
      title: '#8B4513',
      body: '#6B4226',
      accent: '#D2691E',
    },
    fonts: { title: "'Roboto Slab', serif", body: "'Merriweather', serif" },
  },
  {
    id: 'aqua_splash',
    name: { en: 'Aqua Splash', ar: 'رذاذ الماء' },
    colors: {
      previewBg: '#E0FFFF',
      slideBg: 'linear-gradient(135deg, #E6E9F0 0%, #EEF1F5 100%)',
      cardBg: 'rgba(255, 255, 255, 0.6)',
      title: '#008B8B',
      body: '#4682B4',
      accent: '#5F9EA0',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Lato', sans-serif" },
  },
  // Vibrant Themes
  {
    id: 'sunset_drive',
    name: { en: 'Sunset Drive', ar: 'غروب الشمس' },
    colors: {
      previewBg: '#331A2C',
      slideBg: 'linear-gradient(to right, #ff4e50, #f9d423)',
      cardBg: 'rgba(0, 0, 0, 0.2)',
      title: '#FFFFFF',
      body: '#F5F5F5',
      accent: '#000000',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Montserrat', sans-serif" },
  },
  {
    id: 'ocean_breeze',
    name: { en: 'Ocean Breeze', ar: 'نسيم المحيط' },
    colors: {
      previewBg: '#D6E4E2',
      slideBg: 'linear-gradient(to right, #74ebd5, #acb6e5)',
      cardBg: 'rgba(255, 255, 255, 0.4)',
      title: '#006a71',
      body: '#4a5554',
      accent: '#ff7b54',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Poppins', sans-serif" },
  },
  {
    id: 'electric_dreams',
    name: { en: 'Electric Dreams', ar: 'أحلام كهربائية' },
    colors: {
      previewBg: '#120C28',
      slideBg: 'linear-gradient(45deg, #f02fc2 0%, #6094ea 100%)',
      cardBg: 'rgba(0, 0, 0, 0.3)',
      title: '#FFFFFF',
      body: '#EAEAEA',
      accent: '#F9D423',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'mango_passion',
    name: { en: 'Mango Passion', ar: 'شغف المانجو' },
    colors: {
      previewBg: '#FAD961',
      slideBg: 'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
      cardBg: 'rgba(255, 255, 255, 0.4)',
      title: '#8B0000',
      body: '#A0522D',
      accent: '#FF4500',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Lato', sans-serif" },
  },
   {
    id: 'cosmic_latte',
    name: { en: 'Cosmic Latte', ar: 'لاتيه كوني' },
    colors: {
      previewBg: '#EADDCA',
      slideBg: 'linear-gradient(to top, #d299c2 0%, #fef9d7 100%)',
      cardBg: 'rgba(255, 255, 255, 0.5)',
      title: '#483D8B',
      body: '#8A2BE2',
      accent: '#BA55D3',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'aurora',
    name: { en: 'Aurora', ar: 'الشفق القطبي' },
    colors: {
      previewBg: '#0A051A',
      slideBg: 'linear-gradient(to right, #00c6ff, #0072ff)',
      cardBg: 'rgba(0, 0, 0, 0.2)',
      title: '#DAF7A6',
      body: '#FFFFFF',
      accent: '#FFC300',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Poppins', sans-serif" },
  },
  // Professional / Corporate Themes
  {
    id: 'slate_and_gold',
    name: { en: 'Slate & Gold', ar: 'الأردواز والذهب' },
    colors: {
      previewBg: '#2c3e50',
      slideBg: 'linear-gradient(to bottom, #34495e, #2c3e50)',
      cardBg: 'rgba(255, 255, 255, 0.05)',
      title: '#f1c40f',
      body: '#ecf0f1',
      accent: '#3498db',
    },
    fonts: { title: "'Roboto Slab', serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'ivory_tower',
    name: { en: 'Ivory Tower', ar: 'البرج العاجي' },
    colors: {
      previewBg: '#f5f5f5',
      slideBg: 'linear-gradient(to bottom, #ffffff, #f1f1f1)',
      cardBg: 'rgba(255, 255, 255, 0.8)',
      title: '#333333',
      body: '#555555',
      accent: '#007bff',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Lato', sans-serif" },
  },
   {
    id: 'steel_blue',
    name: { en: 'Steel Blue', ar: 'أزرق فولاذي' },
    colors: {
      previewBg: '#4682B4',
      slideBg: 'linear-gradient(135deg, #B0C4DE 0%, #4682B4 100%)',
      cardBg: 'rgba(255, 255, 255, 0.1)',
      title: '#FFFFFF',
      body: '#F0F8FF',
      accent: '#FFD700',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'burgundy_book',
    name: { en: 'Burgundy Book', ar: 'كتاب بورجوندي' },
    colors: {
      previewBg: '#F5F5DC',
      slideBg: 'linear-gradient(to right, #FFF8DC, #FFEBCD)',
      cardBg: 'rgba(255, 255, 255, 0.7)',
      title: '#800000',
      body: '#A52A2A',
      accent: '#D2691E',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Merriweather', serif" },
  },
  {
    id: 'executive',
    name: { en: 'Executive', ar: 'تنفيذي' },
    colors: {
      previewBg: '#1f2937',
      slideBg: 'linear-gradient(145deg, #374151 0%, #111827 100%)',
      cardBg: 'rgba(255, 255, 255, 0.05)',
      title: '#d1d5db',
      body: '#9ca3af',
      accent: '#3b82f6',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Poppins', sans-serif" },
  },
  {
    id: 'harvard_crimson',
    name: { en: 'Harvard Crimson', ar: 'قرمزي هارفارد' },
    colors: {
      previewBg: '#A51C30',
      slideBg: 'linear-gradient(to right, #C9C9C9, #FFFFFF)',
      cardBg: 'rgba(0, 0, 0, 0.02)',
      title: '#A51C30',
      body: '#222222',
      accent: '#808080',
    },
    fonts: { title: "'Merriweather', serif", body: "'Lato', sans-serif" },
  },
  // Unique/Artistic Themes
  {
    id: 'matcha',
    name: { en: 'Matcha', ar: 'ماتشا' },
    colors: {
      previewBg: '#C2DDC3',
      slideBg: 'linear-gradient(to top, #a1c4fd 0%, #c2e9fb 100%)',
      cardBg: 'rgba(255, 255, 255, 0.5)',
      title: '#3A5F0B',
      body: '#556B2F',
      accent: '#8FBC8F',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Poppins', sans-serif" },
  },
  {
    id: 'blueberry_sorbet',
    name: { en: 'Blueberry Sorbet', ar: 'سوربيه التوت' },
    colors: {
      previewBg: '#D8BFD8',
      slideBg: 'linear-gradient(120deg, #a6c0fe 0%, #f68084 100%)',
      cardBg: 'rgba(255, 255, 255, 0.3)',
      title: '#FFFFFF',
      body: '#F0F8FF',
      accent: '#FFDAB9',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Lato', sans-serif" },
  },
   {
    id: 'night_vision',
    name: { en: 'Night Vision', ar: 'رؤية ليلية' },
    colors: {
      previewBg: '#000000',
      slideBg: 'radial-gradient(circle, #2E2E2E, #000000)',
      cardBg: 'rgba(0, 255, 0, 0.05)',
      title: '#00FF00',
      body: '#A9A9A9',
      accent: '#008000',
    },
    fonts: { title: "'Roboto Mono', monospace", body: "'Courier New', monospace" },
  },
  {
    id: 'coral_reef',
    name: { en: 'Coral Reef', ar: 'الشعاب المرجانية' },
    colors: {
      previewBg: '#F0F8FF',
      slideBg: 'linear-gradient(to right, #ffafbd, #ffc3a0)',
      cardBg: 'rgba(255, 255, 255, 0.6)',
      title: '#FF6347',
      body: '#4682B4',
      accent: '#20B2AA',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Poppins', sans-serif" },
  },
  {
    id: 'lavender_fields',
    name: { en: 'Lavender Fields', ar: 'حقول الخزامى' },
    colors: {
      previewBg: '#E6E6FA',
      slideBg: 'linear-gradient(to top, #e1a2b8, #9d95c2)',
      cardBg: 'rgba(255, 255, 255, 0.4)',
      title: '#483D8B',
      body: '#6A5ACD',
      accent: '#9370DB',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'autumn_leaves',
    name: { en: 'Autumn Leaves', ar: 'أوراق الخريف' },
    colors: {
      previewBg: '#FFF8DC',
      slideBg: 'linear-gradient(to right, #DAA520, #B8860B)',
      cardBg: 'rgba(255, 255, 255, 0.1)',
      title: '#FFFFFF',
      body: '#F5DEB3',
      accent: '#FF4500',
    },
    fonts: { title: "'Roboto Slab', serif", body: "'Merriweather', serif" },
  },
  // Retro/Vintage Themes
  {
    id: 'retro_wave',
    name: { en: 'Retro Wave', ar: 'موجة ريترو' },
    colors: {
      previewBg: '#21113C',
      slideBg: 'linear-gradient(to bottom, #ff7e5f, #feb47b)',
      cardBg: 'rgba(0, 0, 0, 0.1)',
      title: '#2C3E50',
      body: '#34495E',
      accent: '#E67E22',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'vintage_newspaper',
    name: { en: 'Vintage Newspaper', ar: 'جريدة قديمة' },
    colors: {
      previewBg: '#F5F5DC',
      slideBg: 'linear-gradient(to bottom, #fdf5e6, #f5e6d3)',
      cardBg: 'rgba(0, 0, 0, 0.03)',
      title: '#5D4037',
      body: '#795548',
      accent: '#A1887F',
    },
    fonts: { title: "'Roboto Slab', serif", body: "'Merriweather', serif" },
  },
  {
    id: 'miami_vice',
    name: { en: 'Miami Vice', ar: 'ميامي فايس' },
    colors: {
      previewBg: '#000000',
      slideBg: 'linear-gradient(to top, #09203f 0%, #537895 100%)',
      cardBg: 'rgba(255, 255, 255, 0.05)',
      title: '#FF00FF',
      body: '#00FFFF',
      accent: '#FFFF00',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'sepia_tone',
    name: { en: 'Sepia Tone', ar: 'بني داكن' },
    colors: {
      previewBg: '#F0EAD6',
      slideBg: 'linear-gradient(to bottom, #f5f5dc, #d2b48c)',
      cardBg: 'rgba(255, 255, 255, 0.5)',
      title: '#5D4037',
      body: '#795548',
      accent: '#8B4513',
    },
    fonts: { title: "'Playfair Display', serif", body: "'Lato', sans-serif" },
  },
  {
    id: 'synthwave',
    name: { en: 'Synthwave', ar: 'سينثويف' },
    colors: {
      previewBg: '#2C0A4A',
      slideBg: 'linear-gradient(135deg, #1A1A2E 0%, #16213E 100%)',
      cardBg: 'rgba(255, 255, 255, 0.05)',
      title: '#E94560',
      body: '#00D1FF',
      accent: '#F9ED69',
    },
    fonts: { title: "'Poppins', sans-serif", body: "'Montserrat', sans-serif" },
  },
  {
    id: 'pop_art',
    name: { en: 'Pop Art', ar: 'فن البوب' },
    colors: {
      previewBg: '#F0E68C',
      slideBg: 'linear-gradient(45deg, #FFD700 0%, #FF69B4 100%)',
      cardBg: 'rgba(255, 255, 255, 0.3)',
      title: '#0000FF',
      body: '#000000',
      accent: '#FF0000',
    },
    fonts: { title: "'Montserrat', sans-serif", body: "'Poppins', sans-serif" },
  },
];


export const CONTENT_TYPES = [
    { id: 'blog_post', en: 'Blog Post', ar: 'تدوينة' },
    { id: 'article', en: 'Article', ar: 'مقالة' },
    { id: 'email', en: 'Email', ar: 'بريد إلكتروني' },
    { id: 'social_media_post', en: 'Social Media Post', ar: 'منشور تواصل اجتماعي' },
];

export const TONES = [
    { id: 'professional', en: 'Professional', ar: 'احترافي' },
    { id: 'casual', en: 'Casual', ar: 'غير رسمي' },
    { id: 'enthusiastic', en: 'Enthusiastic', ar: 'حماسي' },
    { id: 'persuasive', en: 'Persuasive', ar: 'مقنع' },
];

export const LANGUAGES = [
  { code: 'en', name: 'English', arName: 'الإنجليزية' },
  { code: 'ar', name: 'Arabic', arName: 'العربية' },
  { code: 'es', name: 'Spanish', arName: 'الإسبانية' },
  { code: 'fr', name: 'French', arName: 'الفرنسية' },
  { code: 'de', name: 'German', arName: 'الألمانية' },
  { code: 'it', name: 'Italian', arName: 'الإيطالية' },
  { code: 'pt', name: 'Portuguese', arName: 'البرتغالية' },
  { code: 'ru', name: 'Russian', arName: 'الروسية' },
  { code: 'ja', name: 'Japanese', arName: 'اليابانية' },
  { code: 'ko', name: 'Korean', arName: 'الكورية' },
  { code: 'zh', name: 'Chinese', arName: 'الصينية' },
  { code: 'hi', name: 'Hindi', arName: 'الهندية' },
  { code: 'tr', name: 'Turkish', arName: 'التركية' },
  { code: 'pl', name: 'Polish', arName: 'البولندية' },
  { code: 'nl', name: 'Dutch', arName: 'الهولندية' },
];

export const QUICK_PHRASES = [
  { en: "Hello", ar: "مرحباً" },
  { en: "Thank you", ar: "شكراً لك" },
  { en: "How are you?", ar: "كيف حالك؟" },
  { en: "Yes", ar: "نعم" },
  { en: "No", ar: "لا" },
  { en: "Goodbye", ar: "مع السلامة" },
];