import React from 'react';
import { Language } from './types';

export const i18n = {
  [Language.EN]: {
    title: "SciGenius",
    navResearch: "Research Copilot",
    navPrompt: "Prompt Generator",
    navDesign: "Interior Designer",
    // Research
    researchTitle: "Academic Research Copilot",
    researchDescription: "Upload a document to start a conversation, or ask me to find relevant papers.",
    uploadArea: "Drag & drop a file here, or click to select",
    uploading: "Uploading...",
    fileReady: "is ready. Ask me anything about it.",
    askPlaceholder: "Ask a follow-up question...",
    suggestion1: "Summarize the abstract",
    suggestion2: "What are the key findings?",
    suggestion3: "Find related papers",
    thinking: "SciGenius is thinking...",
    sources: "Sources",
    relatedPapers: "Related Papers",
    // Prompt
    promptTitle: "Creative Prompt Generator",
    promptDescription: "Provide a simple topic, and I'll expand it into a detailed, evocative prompt for generative AI.",
    promptPlaceholder: "e.g., a futuristic cityscape at sunset",
    generatePrompt: "Generate Prompt",
    copy: "Copy",
    copied: "Copied!",
    // Design
    designTitle: "AI Interior Designer",
    designDescription: "Reimagine your space. Upload a photo, choose a room type and style, and let AI do the rest.",
    step1: "1. Upload a Photo",
    step2: "2. Choose Room Type",
    step3: "3. Pick a Style",
    selectRoomType: "Select Room Type",
    roomTypes: { living: "Living Room", bedroom: "Bedroom", kitchen: "Kitchen", office: "Office", dining: "Dining Room", bathroom: "Bathroom" },
    redesign: "Redesign Room",
    redesigning: "Redesigning your room... this may take a moment.",
    before: "Before",
    after: "After",
    download: "Download Design",
    // General
    apiKeyError: "Gemini API key is not configured. Please check your environment setup.",
    errorOccurred: "An error occurred. Please try again.",
    connectWithUs: "Connect with us",
    // Auth
    loginRegister: "Login / Register",
    login: "Login",
    register: "Register",
    emailAddress: "Email Address",
    password: "Password",
    signInWithGoogle: "Sign in with Google",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    createAccount: "Create Account",
    logout: "Logout",
  },
  [Language.AR]: {
    title: "عبقري العلوم",
    navResearch: "مساعد البحث العلمي",
    navPrompt: "مولد الأفكار الإبداعية",
    navDesign: "مصمم الديكور الداخلي",
    // Research
    researchTitle: "مساعد البحث العلمي",
    researchDescription: "قم برفع مستند لبدء محادثة، أو اطلب مني البحث عن أوراق بحثية ذات صلة.",
    uploadArea: "اسحب وأفلت ملفًا هنا، أو انقر للاختيار",
    uploading: "جاري الرفع...",
    fileReady: "جاهز. اسألني أي شيء عنه.",
    askPlaceholder: "اطرح سؤالاً...",
    suggestion1: "لخص الملخص",
    suggestion2: "ما هي النتائج الرئيسية؟",
    suggestion3: "ابحث عن أوراق بحثية ذات صلة",
    thinking: "عبقري العلوم يفكر...",
    sources: "المصادر",
    relatedPapers: "أوراق بحثية ذات صلة",
    // Prompt
    promptTitle: "مولد الأفكار الإبداعية",
    promptDescription: "قدم فكرة بسيطة، وسأقوم بتوسيعها إلى موجه مفصل ومثير للذكاء الاصطناعي التوليدي.",
    promptPlaceholder: "مثال: منظر مدينة مستقبلية عند غروب الشمس",
    generatePrompt: "توليد الفكرة",
    copy: "نسخ",
    copied: "تم النسخ!",
    // Design
    designTitle: "مصمم الديكور الداخلي بالذكاء الاصطناعي",
    designDescription: "أعد تصور مساحتك. ارفع صورة، اختر نوع الغرفة والنمط، ودع الذكاء الاصطناعي يقوم بالباقي.",
    step1: "١. ارفع صورة",
    step2: "٢. اختر نوع الغرفة",
    step3: "٣. اختر النمط",
    selectRoomType: "اختر نوع الغرفة",
    roomTypes: { living: "غرفة معيشة", bedroom: "غرفة نوم", kitchen: "مطبخ", office: "مكتب", dining: "غرفة طعام", bathroom: "حمام" },
    redesign: "أعد تصميم الغرفة",
    redesigning: "جاري إعادة تصميم غرفتك... قد يستغرق هذا بعض الوقت.",
    before: "قبل",
    after: "بعد",
    download: "تحميل التصميم",
    // General
    apiKeyError: "مفتاح Gemini API غير مهيأ. يرجى التحقق من إعدادات البيئة الخاصة بك.",
    errorOccurred: "حدث خطأ. يرجى المحاولة مرة أخرى.",
    connectWithUs: "تواصل معنا",
    // Auth
    loginRegister: "تسجيل الدخول / إنشاء حساب",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    signInWithGoogle: "تسجيل الدخول باستخدام جوجل",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    createAccount: "إنشاء حساب",
    logout: "تسجيل الخروج",
  },
};

export const DESIGN_STYLES = [
  { id: 'Modern', name: (lang) => lang === Language.EN ? 'Modern' : 'حديث', imageUrl: 'https://picsum.photos/seed/modern/300/200' },
  { id: 'Minimalist', name: (lang) => lang === Language.EN ? 'Minimalist' : 'بسيط', imageUrl: 'https://picsum.photos/seed/minimalist/300/200' },
  { id: 'Bohemian', name: (lang) => lang === Language.EN ? 'Bohemian' : 'بوهيمي', imageUrl: 'https://picsum.photos/seed/bohemian/300/200' },
  { id: 'Industrial', name: (lang) => lang === Language.EN ? 'Industrial' : 'صناعي', imageUrl: 'https://picsum.photos/seed/industrial/300/200' },
  { id: 'Scandinavian', name: (lang) => lang === Language.EN ? 'Scandinavian' : 'اسكندنافي', imageUrl: 'https://picsum.photos/seed/scandinavian/300/200' },
  { id: 'Coastal', name: (lang) => lang === Language.EN ? 'Coastal' : 'ساحلي', imageUrl: 'https://picsum.photos/seed/coastal/300/200' },
];