const fs = require('fs');
const path = require('path');

// This script is intended to be run as a Build/Post-deployment command in Coolify.
// It reads environment variables from the system and writes them to env.js
// so they are available to the browser at runtime.

const targetPath = path.join(__dirname, 'env.js');

// We check for both standard names and VITE_ prefixed names
const envVars = {
  API_KEY: process.env.API_KEY || process.env.VITE_API_KEY || '',
  SUPABASE_URL: process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || ''
};

const content = `
// Generated by generate_env.js at ${new Date().toISOString()}
window.process = window.process || {};
window.process.env = window.process.env || {};
window.process.env.API_KEY = '${envVars.API_KEY}';
window.process.env.SUPABASE_URL = '${envVars.SUPABASE_URL}';
window.process.env.SUPABASE_ANON_KEY = '${envVars.SUPABASE_ANON_KEY}';
`;

try {
  fs.writeFileSync(targetPath, content);
  console.log('✅ env.js successfully generated.');
  
  // Log which keys were found (masking values)
  Object.keys(envVars).forEach(key => {
      const val = envVars[key];
      const status = val ? `Found (${val.substring(0, 5)}...)` : 'MISSING';
      console.log(`   - ${key}: ${status}`);
  });
  
} catch (err) {
  console.error('❌ Failed to generate env.js:', err);
  process.exit(1);
}